Section html css branch
MICHAELKITH/project_day_2 pull request #3
Opened 2022-12-05 12:12 UTC by MICHAELKITH

Just adding a simple html and css files to the main branching

2022-12-05 12:18 UTC, Abenezer-Tilahun requested changes
Hi @MICHAELKITH  , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻
✔️ No Linters error
✔️ You used correct GitHub Flow.
✔️ Professional README
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ]  Good job for documenting your Readme File Professional, But I recommend to include "Getting Started" section and the section "Future Features", including 1-3 potential features to be added using the the [README template](https://github.com/microverseinc/readme-template)  

_Check the comments below the review._
## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 12:18 UTC, Abenezer-Tilahun commented on index.html
> +    <h1>Hello Microverse ! </h1>
- [ ]  As stated the project requirement Kindly make your added A .css file that includes `one class` with styles for your header (make it in your favorite color).

![Capture](https://user-images.githubusercontent.com/93598189/205635210-2d9d6383-4a6e-4e77-84f3-f531ccaea143.PNG)

2022-12-05 12:32 UTC, MICHAELKITH commented
the css file is added please check

2022-12-05 12:35 UTC, Abenezer-Tilahun commented
Hello @MICHAELKITH  yeah .css file added but it must be with class with styles for your header, Just like "<h1 class="header" >Hello Microverse ! </h1>"

2022-12-05 12:50 UTC, MICHAELKITH commented
okay , i have changed bro you can check now

2022-12-05 13:03 UTC, franclobo requested changes
Hi @MICHAELKITH, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Correct Github flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] **As the last code reviewer suggested, please complete all the sections on the  README file to have a professional repo** 👇🏽 

> Good job for documenting your Readme File Professional, But I recommend to include "Getting Started" section and the section "Future Features", including 1-3 potential features to be added using the the [README template](https://github.com/microverseinc/readme-template)

## Optional suggestions

- [ ] **[OPTIONAL]** Please 🙏🏽 add a title and a description od the activities in your PR for a professional repo.

| Expected PR | Your PR |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/205643815-1bbf113f-d779-4dc2-a022-9abd29be6527.png) | ![image](https://user-images.githubusercontent.com/58642949/205643913-51923388-9cac-408f-9b25-176239b06516.png) |



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 14:49 UTC, MICHAELKITH commented
okay, should upload link for reviewal or you can review from here.

2022-12-05 18:01 UTC, MICHAELKITH commented
@Abenezer-Tilahun  check if i have i done it

2022-12-05 18:21 UTC, Abenezer-Tilahun commented
Hello @MICHAELKITH  yeah you done it, submit for review on your dashboard and it will be approved.

2022-12-06 05:50 UTC, Qoosim approved these changes
#   *Status: Approved* :tada: :heavy_check_mark: 

Hi @MICHAELKITH, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Descriptive PR summary. :heavy_check_mark: 

![](https://camo.githubusercontent.com/894d22fdf31aac32d1cd488fc22318df1eea3204fa6d0129c3d61a99f137ce2d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336b75536f3734345549504a6a634a55456e2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 06:19 UTC, merged